title: Blur
executor:
  name: nodejs
  options:
    entry: index.ts
inputs_def:
  - handle: sharp
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
  - handle: sigma
    json_schema:
      type: number
      minimum: 0.3
      maximum: 100
      ui:options:
        step: 0.1
outputs_def:
  - handle: sharp
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
