executor:
  name: nodejs
  options:
    entry: index.ts
inputs_def:
  - handle: sigma
    json_schema:
      type: number
      ui:options:
        step: 1
      minimum: 1
      maximum: 10
  - handle: sharp
    json_schema:
      contentMediaType: oomol/var
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      ui:widget: any
outputs_def:
  - handle: sharp
    json_schema:
      type:
        - string
        - number
        - integer
        - boolean
        - object
        - array
        - "null"
      contentMediaType: oomol/var
icon: ":fa6-solid:scissors:currentColor:"
